AllCops:
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

# Disable Metric checks for specs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Guardfile'
    - '*.gemspec'

Metrics/LineLength:
  Max: 100
  Exclude:
    - Gemfile
  
Style/Documentation:
  Enabled: false


Style/FormatString:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/TrailingWhitespace:
  Enabled: false
Metrics/AbcSize:
  Max: 30
