sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
install:
  - bundle install --jobs=3 --retry=3 --path=vendor/bundle
cache:
  bundler: false
  directories:
    - vendor/bundle
before_script:
  - unset RACK_ENV
  - unset RAILS_ENV
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.4.0
      gemfile: gemfiles/rails_3.gemfile
services:
  - redis-server
