version: 2
jobs:
  build:
    docker:
      - image: deliveroo/multiruby
    parallelism: 3
    steps: &shared_steps
      - checkout

      # - run:
      #     name: install parallelism script
      #     command: |
      #       curl -fsSL https://git.io/v2Ifs -o ~/circleci-matrix ;
      #       chmod +x ~/circleci-matrix

      # - run: 
      #     name: compute cache key
      #     command: |
      #       cd ~/project &&
      #       cat Gemfile.lock gemfiles/*.lock > .cache-key &&
      #       ruby -v >> .cache-key

      # - type: cache-restore
      #   key: bundle-{{ checksum ".cache-key" }}

      - run:
          name: select build variant
          command: |
            set -ex ;
            case $CIRCLE_NODE_INDEX in
              0) ruby=2.3.4 ; variant=rails_3 ;;
              1) ruby=2.4.1 ; variant=rails_4 ;;
              2) ruby=2.3.4 ; variant=rails_5 ;;
            esac ;
            rbenv local $ROR_RUBY ;
            gem install bundler ;
            bundle config --local gemfile gemfiles/${variant}.gemfile

      - run: 
          name: install dependencies
          command: |
            bundle install --jobs=3 --retry=3 --path=vendor/bundle

      - run:
          name: run tests
          command: |
            unset RACK_ENV &&
            unset RAILS_ENV &&
            bundle exec 

      # - type: cache-save
      #   key: bundle-{{ checksum ".cache-key" }}
      #   paths:
      #     - ~/project/vendor/bundle
      #     - ~/project/vendor/bundle-scaffold

