default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  variables:
    statement_timeout: 200
development:
  <<: *default
  database: ror_testapp_development
test:
  <<: *default
  database: ror_testapp_test
production:
  <<: *default
  database: ror_testapp_production
