#!/usr/bin/env ruby
require 'rubygems'
require 'roo_on_rails/config'
require 'roo_on_rails/harness'
require 'roo_on_rails/sidekiq/loader'

if ARGV.include? 'sidekiq'
  RooOnRails::Sidekiq::Loader.run
else
  module RooOnRails
    Harness.new(try_fix: true, context: Config.load).run
  end
end
