# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda48154d36643e98fd523756e6f7244865938e0a84ff0c95ba20980333949135cde5f60bc599dabdf7285c0c0e3775ce086e87b73aa5ede0bf5c8bfd1085909

test:
  secret_key_base: 1925e7893c6a95a7ed3e85cc80214b94ca1285a08c69c7af1bd1fde693dec7ff976436584fd56d72031fd7e9d03faa53c8ea8d42b14f3dcbc2bae2ad82e5d7e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
