# Google Oauth initializer, generated by RooOnRails

require 'roo_on_rails/rack/google_oauth'

Rails.application.config.middleware.use RooOnRails::Rack::GoogleOauth do |env, data|
  # This is your auth strategy
end
